In [34]:
import numpy as np

# 1. Create a vector with values ranging from 10 to 49.
vector = np.arange(10, 50)
print("Vector:", vector)


Vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [35]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix:\n", matrix_3x3)

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
# 3. Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# 4. Create a 3x3x3 array with random values.
random_array = np.random.random((3, 3, 3))
print("3x3x3 Random Array:\n", random_array)

3x3x3 Random Array:
 [[[0.11117568 0.1143306  0.67780855]
  [0.0972794  0.03722306 0.17195644]
  [0.35370461 0.54911912 0.50146547]]

 [[0.67358175 0.5568076  0.85880765]
  [0.26242474 0.9827889  0.15781935]
  [0.61680005 0.50066736 0.51374271]]

 [[0.25821204 0.02986813 0.47794584]
  [0.72798828 0.78968756 0.31036018]
  [0.92916179 0.07089096 0.97614854]]]


In [38]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
large_random_array = np.random.random((10, 10))
print("Min:", np.min(large_random_array))
print("Max:", np.max(large_random_array))

Min: 0.004913765142230853
Max: 0.9831547310500683


In [39]:
# 6. Create a random vector of size 30 and find the mean value.
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("Mean Value:", mean_value)

Mean Value: 0.4912743993315704


In [40]:
# 7. Normalize a 5x5 random matrix.
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print("Normalized Matrix:\n", normalized_matrix)

Normalized Matrix:
 [[8.36210604e-01 9.81458928e-01 2.78044713e-02 1.26007377e-01
  7.87759328e-01]
 [6.70715251e-01 9.85602814e-01 1.00000000e+00 8.10981832e-01
  7.58479210e-02]
 [4.13900823e-01 2.64150973e-01 5.60061406e-01 5.32953208e-01
  2.72255003e-01]
 [6.00054089e-01 4.46949243e-01 1.84223949e-04 8.93079029e-01
  2.43036154e-01]
 [2.92982093e-01 8.22802978e-01 3.17013165e-01 0.00000000e+00
  8.93911351e-01]]


In [41]:
# 8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
A = np.random.randint(1, 10, (5, 3))
B = np.random.randint(1, 10, (3, 2))
product = np.dot(A, B)
print("Matrix Product:\n", product)

Matrix Product:
 [[ 74 155]
 [ 41 100]
 [ 77 156]
 [ 40  89]
 [ 43 102]]


In [42]:
# 9. Create two 3x3 matrices and compute their dot product.
M1 = np.random.randint(1, 10, (3, 3))
M2 = np.random.randint(1, 10, (3, 3))
dot_product = np.dot(M1, M2)
print("Dot Product:\n", dot_product)

Dot Product:
 [[ 84  46 171]
 [ 39  26 126]
 [ 40  19  90]]


In [43]:
# 10. Given a 4x4 matrix, find its transpose.
matrix_4x4 = np.random.randint(1, 10, (4, 4))
transpose_matrix = matrix_4x4.T
print("Transpose:\n", transpose_matrix)

Transpose:
 [[8 1 6 2]
 [3 1 3 7]
 [3 2 4 9]
 [5 4 8 4]]


In [44]:
# 11. Create a 3x3 matrix and calculate its determinant.
matrix_3x3_det = np.random.randint(1, 10, (3, 3))
determinant = np.linalg.det(matrix_3x3_det)
print("Determinant:", determinant)

Determinant: -65.99999999999997


In [45]:
# 12. Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A ⋅ B ).
A = np.random.randint(1, 10, (3, 4))
B = np.random.randint(1, 10, (4, 3))
matrix_product = np.dot(A, B)
print("Matrix Product (A . B):\n", matrix_product)

Matrix Product (A . B):
 [[209 195 169]
 [ 91  72  72]
 [198 183 149]]


In [46]:
# 13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.
matrix_3x3 = np.random.randint(1, 10, (3, 3))
vector_3 = np.random.randint(1, 10, (3, 1))
matrix_vector_product = np.dot(matrix_3x3, vector_3)
print("Matrix-Vector Product:\n", matrix_vector_product)

Matrix-Vector Product:
 [[49]
 [82]
 [67]]


In [47]:
# 14. Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.
A = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 1))
x = np.linalg.solve(A, b)
print("Solution (x):\n", x)

Solution (x):
 [[-0.5       ]
 [ 1.03571429]
 [ 0.21428571]]


In [48]:
# 15. Given a 5x5 matrix, find the row-wise and column-wise sums.
matrix_5x5 = np.random.randint(1, 10, (5, 5))
row_sums = np.sum(matrix_5x5, axis=1)
column_sums = np.sum(matrix_5x5, axis=0)
print("Row-wise Sums:", row_sums)
print("Column-wise Sums:", column_sums)

Row-wise Sums: [19 32 17 20 31]
Column-wise Sums: [26 29 19 15 30]
